<?php /* Smarty version 2.6.26, created on 2018-10-04 14:02:55
         compiled from member_login.htm */ ?>
<!DOCTYPE html><html><head><meta charset="utf-8" /><title>铭东物流转运系统</title><link href="favicon.ico" rel="shortcut icon" type="image/x-icon" /><link href="themes/default/css/common.css" rel="stylesheet" type="text/css" /><link href="themes/default/css/page.css" rel="stylesheet" type="text/css" /><?php echo '<script type="text/javascript" src="themes/default/js/jquery-1.8.1.min.js"></script><script type="text/javascript" src="themes/default/js/common.js"></script><script type="text/javascript" src="themes/default/js/user.js"></script><!--[if IE 6]><script src="js/DD_belatedPNG_0.0.8a-min.js"></script><script>  DD_belatedPNG.fix(\'.ie6png,.ie6png:hover\');</script><![endif]-->'; ?>
</head><body><?php $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "header.htm", 'smarty_include_vars' => array()));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
 ?><div class="login">  <div class="main_login">    <div class="ml_left">	  <h1>欢迎登陆铭东转运用户中心</h1>	  <p class="p_info">登陆后...</p>	  <ul>	    <li>派件提醒、签收提醒，免费短信发送到您<span>手机、微信、易信；</span></li>		<li>投诉建议，看得见的反馈；</li>		<li>在线寄件，轻松下单</li>	  </ul>	  <a href="index.php?act=member_register">注册账号</a>	</div>	<div class="ml_right">	  <form enctype="multipart/form-data" action="user.php?act=member_account_login" method="post" name="theForm" onsubmit="return validate()" name="theForm">	      <h2>账号密码登录</h2>	      <div class="div_account">	      	<span class="span_txts"><input class="ipt-txts" type="text" name="username"  placeholder="邮箱/手机号码/用户名" /></span>	      </div>	      <div class="div_password">	      	<span class="span_txts">	      	<input class="ipt-txts" type="password" name="password"  placeholder="请输入密码" /></span>	      </div>	      <!-- 	      <div class="div_account">	      <span class="span_txts">	      <input class="ipt-txts" type="text" id="captcha" name="captcha" style="width:162px;" placeholder="请输入验证码" />	      </span>	      <img src="index.php?act=captcha&<?php echo $this->_tpl_vars['random']; ?>
" alt="CAPTCHA" border="1" onclick= this.src="index.php?act=captcha&"+Math.random() style="cursor: pointer;" title="<?php echo $this->_tpl_vars['lang']['click_for_another']; ?>
" />	      </div> -->		  <button type="submit" class="button">登&nbsp;&nbsp;录</button>		  <span><a href="index.php?act=forget_password">注册邮件找回密码</a></span>     </form>	</div>  </div></div><?php $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "footer.htm", 'smarty_include_vars' => array()));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
 ?></body></html><script type="text/javascript"><?php echo 'document.forms[\'theForm\'].elements[\'username\'].focus();/** * 表单验证 */function validate(){  validator = new Validator("theForm");  validator.required("username",  username_notnull);  validator.required("password", password_notnull);  //validator.required("captcha", captcha_notnull);  return validator.passed();}'; ?>
</script>