<?php /* Smarty version 2.6.26, created on 2018-09-12 06:26:35
         compiled from member_register.htm */ ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xmlns="http://www.w3.org/1999/xhtml"><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><title>铭东物流转运系统</title><link href="favicon.ico" rel="shortcut icon" type="image/x-icon" /><link href="themes/default/css/common.css" rel="stylesheet" type="text/css" /><link href="themes/default/css/page.css" rel="stylesheet" type="text/css" /><script type="text/javascript" src="themes/default/js/jquery-1.8.1.min.js"></script><script type="text/javascript" src="themes/default/js/common.js"></script><script type="text/javascript" src="themes/default/js/user_register.js"></script><!--[if IE 6]><script src="js/DD_belatedPNG_0.0.8a-min.js"></script><script>  DD_belatedPNG.fix('.ie6png,.ie6png:hover');</script><![endif]--> </head> <body><?php $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "header.htm", 'smarty_include_vars' => array()));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
 ?><div class="reg">  <div class="main_reg">    <div class="ml_left">		<img src="themes/default/images/zhuce.jpg" style="width:100%">	  <h1>欢迎登陆铭东转运用户中心</h1>	  <p class="p_info">登陆后...</p>	  <ul>	    <li>派件提醒、签收提醒，免费短信发送到您<span>手机、微信、易信；</span></li>		<li>投诉建议，看得见的反馈；</li>		<li>在线寄件，轻松下单</li>	  </ul>	  <a href="index.php?act=member_login">已有账户，立即登录</a>	</div>	<div class="ml_right">      <?php if ($this->_tpl_vars['s_member_register'] == '1'): ?>      	<span class="span_required"><?php echo $this->_tpl_vars['lang']['s_member_register']; ?>
</span>  	  <?php else: ?>	  <form id="formUser" name="formUser" method="post" action="user.php?act=member_register" onsubmit="return validate()">       <table>	     <tr>		   <td class="td_name">用户名：</td>		   <td class="td_txts">		   		<input type="text" class="ipt-txtss" id='username' name="username" placeholder="用户名" onblur="is_registered(this.value);" />		   	</td> 		 </tr>		 <tr><td></td><td><span class="span_required" id='username_notice'></span></td></tr>		  <tr>		   <td class="td_name">密码：</td><td class="td_txts"><input type="password" class="ipt-txtss" onblur="check_password(this.value);" id="password" name="password" placeholder="请输入密码" /></td>		 </tr>		 <!-- 		 <tr>		   <td></td><td><img src="themes/default/images/reg1.png" /></td>		 </tr> -->		 <tr><td></td><td><span class="span_required" id='password_notice'></span></td></tr>		 <tr>		   <td class="td_name">确认密码：</td>		   <td class="td_txts">		   	<input type="password" class="ipt-txtss" id="pwds" name="pwds" placeholder="请输入确认密码" onblur="check_conform_password(this.value)" />		   </td>		 </tr>		 <tr><td></td><td><span class="span_required" id='conform_password_notice'></span></td></tr>		  <tr>		   <td class="td_name">邮箱：</td>		   <td class="td_txts">		   	<input type="text" class="ipt-txtss" id="e_mail" name="e_mail"  placeholder="请输入邮箱" onblur="email_is_registered(this.value)"/></td>		 </tr>		 <tr><td></td><td><span class="span_required" id='e_mail_notice'></span></td></tr>		 <tr>		   <td class="td_name">QQ：</td><td class="td_txts"><input type="text" class="ipt-txtss" name="qq"  placeholder="请输入QQ号码"/></td>		 </tr>		 <tr>		   <td class="td_name">手机号：</td><td class="td_txts"><input type="text" class="ipt-txtss" id="tel" name="tel" onblur="tel_is_registered(this.value)" placeholder="请输入手机号"/></td>		 </tr>		 <tr><td></td><td><span class="span_required" id='tel_notice'></span></td></tr>		 <tr>		   <td class="td_name">密码提示问题：</td>	       <td class="td_txts">		   <input type="text" name="password_question" class="ipt-txtss" placeholder="请输入密码"/>	       <!-- 	       <select class="ipt-txtss" name="password_question">		        <option>选择问题</option>		        <option>我最崇拜的偶像名字是？</option>		      </select>		    -->		   </td>		 </tr>		 <tr>		   <td class="td_name">密码提示答案：</td><td class="td_txts">		   	<input type="password" class="ipt-txtss" name="password_answer" placeholder="请输入答案" />		   </td>		 </tr>		 <tr>		   <td class="td_name">我的推荐码：</td><td class="td_txts">		   <input type="text" id="refencer_recommend_code" name="refencer_recommend_code" class="ipt-txtss" onblur="refencer_recommend_code_is_exist(this.value)" value="<?php echo $this->_tpl_vars['recommend']; ?>
"  placeholder="若有推荐码，请输入答案" />		   </td>		 </tr>		 <tr><td></td><td><span class="span_required" id='refencer_recommend_code_notice'></span></td></tr>		 <!--<tr>-->		 	<!--<td class="td_name">当前所在仓库：</td>-->		 	<!--<td class="td_txts"><?php echo $this->_tpl_vars['warehouse']['HouseName']; ?>
</td>-->		 <!--</tr>-->	     <tr class="trs">		   	<td></td><td class="td_txts">			 我已经阅读并同意：			 <a href="user.php?act=protocol" target="_blank" style="color:blue">用户协议</a></td>		 </tr>	     <tr class="trs">		   <td>      	   </td>      	   <td class="td_txts">      	   	<button class="bottons" name="Submit" type="submit">提交注册</button>      	   </td>		 </tr>	   </table>     </form>     <?php endif; ?>	</div>	<div class="clear"></div>  </div></div><?php $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "footer.htm", 'smarty_include_vars' => array()));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
 ?> </body> </html>